In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [18]:
df = pd.read_csv('dataset/house_price_dataset.csv')
df.tail()

,size_aana,size_ropani,location,floors,house_age_years,price_npr
1195,6.27,0.392,Gongabu,2.5,24,20680000.0
1196,9.59,0.599,Baneshwor,2.5,13,40951000.0
1197,13.97,0.873,Jhamsikhel,2.0,2,78582000.0
1198,16.50,1.031,Budhanilkantha,0.0,19,40805000.0
1199,2.18,0.136,Chabahil,2.0,26,11192000.0

In [3]:
y = df['price_npr']

In [4]:
del df['price_npr']

In [5]:
locations = pd.get_dummies(df['location']).astype(int)

In [6]:
del df['location']

In [7]:
df=pd.concat([df,locations],axis=1)

In [8]:
del df['size_ropani']

In [9]:
X = df

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
X_train

,size_aana,floors,house_age_years,Baluwatar,Baneshwor,Bhaktapur,Boudha,Budhanilkantha,Chabahil,Gongabu,Jhamsikhel,Kalanki,Kalimati,Kirtipur,Koteshwor,Lazimpat,Naxal,New Baneshwor,Sanepa
331,16.23,2.5,20,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
409,5.44,2.0,10,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
76,15.58,2.0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
868,45.60,2.0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
138,16.70,2.5,6,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044,4.05,0.0,27,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1095,53.12,1.0,12,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1130,6.92,0.0,13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
860,5.85,0.0,27,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1126,8.64,1.0,22,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
model = LinearRegression()
model.fit(X_train, y_train) ###Training phase

LinearRegression()

In [13]:
print('Intercept:', model.intercept_)
print('Coefficient:', model.coef_)

Intercept: 6145322.929727629
Coefficient: [  3501973.01304593   2227057.24322236   -288452.00283914
  33174286.94273959   1206700.60164427 -28689716.68247237
  -7991566.61665977 -20633733.8935129   -4432801.54614976
 -16382068.72103312  14803988.4678202  -14539552.42503028
  -8490092.98831284 -24102738.45512374 -10345011.97866113
  30700234.43617596  36068553.85116125  -1328372.41180944
  20981891.41922424]

In [14]:
y_predict=  model.predict(X_test)

In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(y_test,y_predict )

0.880784680260119