In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
df = pd.read_csv('test.csv')

In [10]:
df

     ID        Name   Age Department   Salary    JoinDate
0     1    Person_1  74.0         HR      NaN  2020-01-01
1     2    Person_2  66.0         HR  61485.0  2020-01-02
2     3    Person_3   NaN         HR      NaN  2020-01-03
3     4    Person_4  36.0         IT  77746.0  2020-01-04
4     5    Person_5  42.0  Marketing  70217.0  2020-01-05
..  ...         ...   ...        ...      ...         ...
95   96   Person_96  39.0    Finance  98298.0  2020-04-05
96   97   Person_97  52.0         IT  75606.0  2020-04-06
97   98   Person_98  79.0         HR  60493.0  2020-04-07
98   99   Person_99  33.0        NaN  84543.0  2020-04-08
99  100  Person_100  71.0    Finance  38743.0  2020-04-09

[100 rows x 6 columns]

In [11]:
df.isnull().values.any()

np.True_

In [12]:
df.isnull()

       ID   Name    Age  Department  Salary  JoinDate
0   False  False  False       False    True     False
1   False  False  False       False   False     False
2   False  False   True       False    True     False
3   False  False  False       False   False     False
4   False  False  False       False   False     False
..    ...    ...    ...         ...     ...       ...
95  False  False  False       False   False     False
96  False  False  False       False   False     False
97  False  False  False       False   False     False
98  False  False  False        True   False     False
99  False  False  False       False   False     False

[100 rows x 6 columns]

In [30]:
df[['Age','Salary']][3:9]

    Age   Salary
3  36.0  77746.0
4  42.0  70217.0
5  36.0  65850.0
6   NaN  37948.0
7  22.0  74914.0
8  46.0  85512.0

In [27]:
df['Age']

0     74.0
1     66.0
2      NaN
3     36.0
4     42.0
      ...
95    39.0
96    52.0
97    79.0
98    33.0
99    71.0
Name: Age, Length: 100, dtype: float64

In [7]:
data = {
    "name": [
        "Suman", "Prem", "Rohit", "Dipak", "Santosh",
        "Aarav", "", "Riya", "Bibek", "",
        "Kiran", "Prakash", "", "Roshan", "Manish",
        "", "Bikash", "Sagar", "Nabin", "Raj"
    ],

    "age": [
        21, 22, 20, 23, 21,
        24, 20, 22, 23, 21,
        25, 22, 20, 24, 23,
        21, 22, 25, 20, 24
    ],

    "marks": [
        85, 90, 78, 88, 67,
        92, 76, 81, 74, 95,
        69, 87, 91, 72, 84,
        79, 66, 89, 73, 93
    ],

    "city": [
        "Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Bhaktapur",
        "Kathmandu", "", "Lalitpur", "Kathmandu", "Bhaktapur",
        "Pokhara", "Kathmandu", "Biratnagar", "Lalitpur", "Bhaktapur",
        "Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Kathmandu"
    ]
}

In [8]:
dp = pd.DataFrame(data)

dp.index = [
    "student1", "student2", "student3", "student4", "student5",
    "student6", "student7", "student8", "student9", "student10",
    "student11", "student12", "student13", "student14", "student15",
    "student16", "student17", "student18", "student19", "student20"
]

In [75]:
dp

              name  age  marks        city
student1     Suman   21     85   Kathmandu
student2      Prem   22     90     Pokhara
student3     Rohit   20     78  Biratnagar
student4     Dipak   23     88    Lalitpur
student5   Santosh   21     67   Bhaktapur
student6     Aarav   24     92   Kathmandu
student7             20     76
student8      Riya   22     81    Lalitpur
student9     Bibek   23     74   Kathmandu
student10            21     95   Bhaktapur
student11    Kiran   25     69     Pokhara
student12  Prakash   22     87   Kathmandu
student13            20     91  Biratnagar
student14   Roshan   24     72    Lalitpur
student15   Manish   23     84   Bhaktapur
student16            21     79   Kathmandu
student17   Bikash   22     66     Pokhara
student18    Sagar   25     89  Biratnagar
student19    Nabin   20     73    Lalitpur
student20      Raj   24     93   Kathmandu

In [9]:
dp.loc['student8','city']

'Lalitpur'

In [10]:
dp.iloc[7,3]

'Lalitpur'

In [12]:
df.isnull().sum()

ID             0
Name           0
Age           15
Department    17
Salary        15
JoinDate       0
dtype: int64